swagger: '2.0'

info:
  title: User API
  version: "0.1.0"

paths:
  /ciserver/acess:
    post:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.get_user_info
      summary: The repository has changed.
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              message:
                type: string
                description: information
