include_recipe 'ci_server::install_wget'
include_recipe 'ci_server::install_unzip'
include_recipe 'ci_server::install_python3.6_and_tools'
include_recipe 'ci_server::install_ngrok'
include_recipe 'ci_server::install_handler'
