swagger: '2.0'

info:
  title: User API
  version: "0.1.0"

paths:
  /ciserver/pullrequest/updatepackages:
    post:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.get_pullrequest_packages
      summary: Update packages needed to install.
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              command_return:
                type: string
                description: User pullrequest information.
