include_recipe 'mirror::packages_config'
include_recipe 'mirror::packages_download'
include_recipe 'mirror::mirror_config'
include_recipe 'mirror::mirror_packages'
include_recipe 'mirror::sshd_config'
include_recipe 'mirror::sshd_restart'
