include_recipe 'mirror_server::mirror_server_config'
include_recipe 'mirror_server::packages_config'
include_recipe 'mirror_server::magic'
include_recipe 'mirror_server::install_packages'
include_recipe 'mirror_server::config_ssh'
include_recipe 'mirror_server::init_ssh'
