swagger: '2.0'

info:
  title: User API
  version: "0.1.0"

paths:
  /ci_server/repository_changed:
    post:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.notify_repository_change
      summary: A new pull request has appeared
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              command_return:
                type: string
                description: User pull request info
