swagger: '2.0'

info:
  title: User API
  version: "0.1.0"

paths:
  /ciprovision:
    post:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.set_pullrequest_info
      summary: The repository has changed..
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/RequestAcepted'
      responses:
         '200':
           description: 'Information acepted'


definitions:
  RequestAcepted:
    type: object
    properties:
      name: { type: string }
